input.onButtonPressed(Button.A, function () {
    turtle.pen(TurtlePenMode.Up)
    turtle.setPosition(2, 2)
    turtle.pen(TurtlePenMode.Down)
    turtle.forward(1)
    turtle.pen(TurtlePenMode.Up)
    turtle.turnLeft()
    turtle.forward(1)
    turtle.pen(TurtlePenMode.Down)
    turtle.back(1)
    turtle.pen(TurtlePenMode.Up)
    turtle.back(1)
    turtle.pen(TurtlePenMode.Down)
    turtle.turnLeft()
    turtle.forward(1)
    turtle.pen(TurtlePenMode.Up)
    turtle.forward(1)
    turtle.turnRight()
    turtle.pen(TurtlePenMode.Down)
    turtle.forward(3)
    turtle.home()
})
basic.forever(function () {
	
})
